env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
rules:
  {
    'prettier/prettier': 'error',
    'no-console': 'off',
    'import/extensions': 'off',
  }
